/**
 * Deterministic emission of the token contract — GENESIS 03 §XI demands the
 * contract "in CSS custom properties and JSON". One typed source (tokens.ts)
 * emits both; the committed artifacts are test-asserted byte-identical to
 * this output ("inspectable, not asserted" — the dormancy-standard precedent
 * applied to design law: drift between source and artifact is impossible to
 * commit silently).
 */
import {
  CONTRACT_VERSION,
  bodyLineHeight,
  candle,
  deskStaggerMs,
  duration,
  easing,
  errata,
  font,
  gold,
  ground,
  iconStrokePx,
  ink,
  layout,
  pencil,
  reducedMotion,
  rubricationBleedMs,
  semantic,
  severityCastOpacity,
  severityStops,
  severityTextStops,
  smallCapsTracking,
  space,
  turn,
  typeScale,
} from './tokens.ts';
import { oklchCss } from './color.ts';

const px = (n: number): string => `${n}px`;
const ms = (n: number): string => `${n}ms`;

/** Custom-property names follow GENESIS 03's own naming where canon names
 * them (--canvas, --ink-body, --gold-bright, --ease-considered, ...). */
export function cssProperties(): ReadonlyArray<readonly [string, string]> {
  return [
    // Ground (§II) — obsidian is the table; it never carries text (§I).
    ['--obsidian-0', ground.obsidian0],
    ['--canvas', ground.canvas],
    ['--surface', ground.surface],
    ['--raised', ground.raised],
    // Ink (§II)
    ['--ink-emphasis', ink.emphasis],
    ['--ink-primary', ink.primary],
    ['--ink-body', ink.body],
    ['--ink-secondary', ink.secondary],
    ['--ink-muted', ink.muted],
    ['--ink-ghost', ink.ghost],
    // Gold (§II — the Gold Law)
    ['--gold', gold.base],
    ['--gold-bright', gold.bright],
    ['--gold-dim', gold.dim],
    ['--gold-ghost', gold.ghost],
    // Semantics (§II) — never travel alone
    ['--heal', semantic.heal],
    ['--wound', semantic.wound],
    ['--arcane', semantic.arcane],
    // Provenance (§III)
    ['--pencil', pencil],
    // Condition severity ramp (§II v2) + derived text register
    ...severityStops.map(
      (s, i) => [`--severity-${i + 1}`, oklchCss(s)] as const,
    ),
    ...severityTextStops.map(
      (s, i) => [`--severity-text-${i + 1}`, oklchCss(s)] as const,
    ),
    ['--severity-cast-opacity', String(severityCastOpacity)],
    // Motion (§VI) — the four registers; nothing else exists
    ['--dur-micro', ms(duration.microMs)],
    ['--dur-state', ms(duration.stateMs)],
    ['--dur-transition', ms(duration.transitionMs)],
    ['--dur-ceremony', ms(duration.ceremonyMs)],
    ['--ease-considered', easing.considered],
    ['--ease-reveal', easing.reveal],
    ['--ease-dismiss', easing.dismiss],
    // Motion, component layer (§VI v2)
    ['--turn-overlap', String(turn.overlap)],
    ['--rubrication-bleed', ms(rubricationBleedMs)],
    ['--desk-stagger', ms(deskStaggerMs)],
    ['--candle-period', ms(candle.periodMs)],
    ['--candle-opacity-min', String(candle.opacityMin)],
    ['--candle-opacity-max', String(candle.opacityMax)],
    // Typography (§IV)
    ['--font-display', font.display],
    ['--font-mechanics', font.mechanics],
    ['--font-data', font.data],
    ['--type-footnote', px(typeScale.footnote)],
    ['--type-caption', px(typeScale.caption)],
    ['--type-body', px(typeScale.body)],
    ['--type-section', px(typeScale.section)],
    ['--type-chapter', px(typeScale.chapter)],
    ['--type-display', px(typeScale.display)],
    ['--type-hero', px(typeScale.hero)],
    ['--leading-body', String(bodyLineHeight)],
    ['--tracking-smallcaps', smallCapsTracking],
    // Space & layout (§V, §X)
    ['--space-compact', px(space.compactPx)],
    ['--space-element', px(space.elementPx)],
    ['--space-section', px(space.sectionPx)],
    ['--margin-editorial', px(space.editorialMarginPx)],
    ['--touch-target', px(space.touchTargetPx)],
    ['--touch-target-tremor', px(space.tremorTargetPx)],
    ['--layout-phone-max', px(layout.phoneMaxPx)],
    ['--layout-desktop-min', px(layout.desktopMinPx)],
    // Iconography (§VIII)
    ['--icon-stroke', px(iconStrokePx)],
  ];
}

export function emitCss(): string {
  const props = cssProperties()
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');
  return `/* GENERATED by @ash-archive/ledger-tokens — DO NOT EDIT.
 * Source: src/tokens.ts (every value canon-cited there).
 * Contract: ${CONTRACT_VERSION} · GENESIS 03 (the Ledger System) · page law only (ADR-SH2-A).
 */
:root {
${props}
}

/* GENESIS 03 §VI reduced-motion law: turns become 200ms cross-fades; all
 * else ≤120ms or instant. Ceremony is never skippable-by-default but always
 * reducible — sacredness must not tax accessibility. */
@media (prefers-reduced-motion: reduce) {
  :root {
    --dur-state: ${ms(reducedMotion.othersMaxMs)};
    --dur-transition: ${ms(reducedMotion.othersMaxMs)};
    --dur-ceremony: ${ms(reducedMotion.othersMaxMs)};
    --dur-turn-reduced: ${ms(reducedMotion.turnCrossfadeMs)};
    --candle-opacity-min: 1;
  }
}
`;
}

export function emitJson(): string {
  const doc = {
    $contract: CONTRACT_VERSION,
    $source: 'GENESIS 03 — the Ledger System (page law; ADR-SH2-A jurisdiction)',
    ground,
    ink,
    gold,
    semantic,
    pencil,
    severity: {
      stops: severityStops.map(oklchCss),
      textStops: severityTextStops.map(oklchCss),
      castOpacity: severityCastOpacity,
    },
    motion: {
      duration,
      easing,
      turn,
      rubricationBleedMs,
      deskStaggerMs,
      candle,
      reducedMotion,
    },
    typography: { font, scale: typeScale, bodyLineHeight, smallCapsTracking },
    space,
    layout,
    icon: { strokePx: iconStrokePx },
    errata,
  };
  return JSON.stringify(doc, null, 2) + '\n';
}
